apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: airflow
type: Opaque
data:
  aws_access_key_id: QUtJQVIzRVVOWlRaWUE0RDM0T0w=
  aws_secret_access_key: Z2VlTk1ORmNCY0YzSzZYMi8rYlY0ZjNiakw5NUlpd1RQRXFWYW15Qg==

---

apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: airflow
type: Opaque
data:
  postgres_password: dmluaWV0bGF3cw==

---

apiVersion: v1
kind: Secret
metadata:
    name: redshift-credentials
    namespace: airflow
type: Opaque
data:
  redshift_password: RXRsLXZpbmktYXdzLTE=

---

apiVersion: v1
kind: Secret
metadata:
    name: token-credential
    namespace: airflow
type: Opaque
data:
  token: Z2hwX0xYaXVjWllZb1MwMHdNMXA2QVVaQk5DVXZHVlZOSTNmTmhRRw==

