apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: airflow
type: Opaque
data:
  aws_access_key_id: QUtJQTVJRVU0U1RBU0JWUUpYS04=
  aws_secret_access_key: ekw2a2RoejVHNVVEUGxGdFNTVmhLdEtSVW5DYlQ5aGVUM0dSdSsyUw==

---

apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: airflow
type: Opaque
data:
  postgres_password: dmluaWV0bGF3cw==

---

apiVersion: v1
kind: Secret
metadata:
    name: redshift-credentials
    namespace: airflow
type: Opaque
data:
  redshift_password: RXRsLXZpbmktYXdzLTE=

