apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: airflow
type: Opaque
data:
  aws_access_key_id: QUtJQVMyNjNWMjNQUVNDTEVJTzc=
  aws_secret_access_key: Tml6eFljdGs0bGYvUVFOL2FGV21Jd3Q1bGFWcngxenZLRWllRnN2ZQ==

---

apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: airflow
type: Opaque
data:
  postgres_password: dmluaWV0bGF3cw==

---

apiVersion: v1
kind: Secret
metadata:
    name: redshift-credentials
    namespace: airflow
type: Opaque
data:
  redshift_password: RXRsLXZpbmktYXdzLTE=

---

apiVersion: v1
kind: Secret
metadata:
    name: token-credential
    namespace: airflow
type: Opaque
data:
  token: Z2hwXzlZMms0Smpic1Uya2lGSkgxOWxsekx0ZVh0bW5oODRYakJoNA==