apiVersion: v1
kind: Secret
metadata:
  name: private-bgd-repo
  namespace: argocd-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/camposvinicius/aws-etl.git
  password: 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
  username: camposvinicius