name: 'Lambda Function and Your Dependencies'

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies and Zip Folder
      working-directory: k8s/lambda-function
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt --target .
        zip -r lambda_function.zip .