name: 'Python Dependencies'

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r k8s/lambda-function/requirements.txt --target k8s/lambda-function
    
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r lambda-function.zip lambda-function
